services:
  
  db:
    image: mysql:8.0.43
    container_name: mysql-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: approotpass
      MYSQL_DATABASE: urldb
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppass
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 3s
      retries: 5
  
  migrate:
    image: migrate/migrate
    restart: "no"
    depends_on: 
      db: 
        condition: service_healthy
    volumes:
      - ./migrations:/migrations
    command: [
      "-path", "/migrations",
      "-database", "mysql://appuser:apppass@tcp(db:3306)/urldb",
      "up"
    ]
  
  backend:
    build: .
    container_name: go-url-shortener
    ports:
      - "4000:4000"
    depends_on:
      - db
      - migrate

volumes:
  db_data: