CREATE TABLE IF NOT EXISTS urls (
    id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    short_code VARCHAR(20) NOT NULL,
    original_url TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

